update

diff --git a/.github/workflows/pipline.yml b/.github/workflows/pipline.yml
--- a/.github/workflows/pipline.yml
+++ b/.github/workflows/pipline.yml
@@ -63,11 +63,23 @@ jobs:
     runs-on: ubuntu-latest
     needs: test
     steps:
+ 
+      - name: Notify Build Start
+        uses: act10ns/slack@v2
+        with:
+          status: starting
+          message: |
+              *Docker Build Started*
+               Building image ${{ env.IMAGE_NAME }}
+               Branch: ${{ github.ref }}
+               Run Number: ${{ env.BUILD_NUMBER }}   
+       
       - name: Checkout code
         uses: actions/checkout@v4
 
       - name: Build Docker image
-        run: docker build -t ${{ env.IMAGE_NAME }} .
+        id: build
+        run: docker build -t ${{ env.IMAGE_NAME }} . || echo "::set-output name=status::failure"
 
       - name: Login to DockerHub
         uses: docker/login-action@v3
@@ -87,11 +99,33 @@ jobs:
       - name: push image latest
         run: docker push ${{ env.IMAGE_NAME }}:latest
 
+      - name: Notify Build Results
+        if: always()
+        uses: act10ns/slack@v2
+        with:
+          status: ${{ steps.build.outputs.status || job.status }}
+          message: |
+            *Docker Build Results* (${{ job.status }})
+            Image: ${{ env.IMAGE_NAME }}:${{ env.BUILD_NUMBER }}
+            ${{ steps.build.outputs.status == 'failure' && ':x: Build failed!' || ':white_check_mark: Build succeeded!' }}
+            ${{ steps.build.outputs.status == 'failure' && 'Check the workflow run for build errors.' || 'Image successfully pushed to Docker Hub.' }}
+
   deployment:
     runs-on: ubuntu-latest
     needs: build-and-push
     steps:
+
+      - name: Notify Deployment Start
+        uses: act10ns/slack@v2
+        with:
+          status: starting
+          message: |
+            *Starting Deployment*
+            Version: ${{ env.BUILD_NUMBER }}
+            Environment: Development
+
       - name: Connect via SSH and deploy
+        id: deploy
         uses: appleboy/ssh-action@v1
         with:
           host: ${{ secrets.HOST }}
@@ -101,7 +135,7 @@ jobs:
             cd /home/user
             sudo git pull
             sudo docker compose pull
-            sudo docker compose up -d --force-recreate --remove-orphans
+            sudo docker compose up -d --force-recreate --remove-orphans || exit 1
 
           
             #- name: check folders and filehhhhhhh
@@ -115,6 +149,18 @@ jobs:
                 #echo "checking node version..."   
                 #node -v
                 #echo "Node version checked."
+
+      - name: Notify Deployment Results
+        if: always()
+        uses: act10ns/slack@v2
+        with:
+            status: ${{ steps.deploy.outcome == 'failure' && 'failure' || 'success' }}
+            channel: "#workflows"
+            message: |
+                *Deployment Results* (${{ job.status }})
+                Version: ${{ env.BUILD_NUMBER }}
+                ${{ steps.deploy.outcome == 'failure' && ':x: Deployment failed!' || ':white_check_mark: Deployment succeeded!' }}
+                ${{ steps.deploy.outcome == 'failure' && 'Check the workflow run for deployment errors.' || 'Application successfully deployed!' }}
 
 #name: Pipeline backend
 
